### ISSUE TITLE
Assalomu aleykum! Doston, yaxshimisiz?  Shu proyektning header qismida hover aktiv holatlarida ozgina kamchilik borga o'xshaydi. Shularni to'g'irlab qo'ysak yaxshi bo'lar edi!

### ISSUE THREAD

**Issue by NozilaXudoyberdiyeva** [NozilaXudoyberdiyeva/myteam#6]
![image](https://user-images.githubusercontent.com/117085295/206892415-aa494fa6-538d-425e-8ba2-6fb94633d3f5.png)

**Comment by HomidovDoston** [comment]
Asalomu aleykum ! va aleykum assalom , mashaalloh yaxshi ! kamchilikni etganiz uchun raxmat 🙂,tez orada xato to'g'irlanadi
